### ISSUE TITLE
Nextcloud 29 + 30 compatibility

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/nc_ext_dav_push#12]
Test with Nextcloud 30 (or at least have a look into the breaking API notes) and mark as compatible

**Comment by JonathanTreffler** [comment]
I don't think any of the NC 30 breaking changes (https://docs.nextcloud.com/server/latest/developer_manual//app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html) affect us so I am marking the app as compatible.
