### ISSUE TITLE
installed, but client doesn't show push availability

### ISSUE THREAD

**Issue by gdt** [bitfireAT/nc_ext_dav_push#27]
[Sorry if this doesn't belong on issues, but I'm guessing with this being experimental reports are useful.   Resolved and you can hit close, but things felt flaky during setup.]

My setup:
  - Nextcloud 28.0.6, php 8.2, on NetBSD 9 with nginx and php_fpm
  - calendar, contacts, tasks available via caldav/carddav, working fine for years
  - Pixel running CalyxOS
  - DAVx5 4.4.2-ose installed via IzzyOnDroid
  - UP running via Conversations, ejabberd using mod_push, working with Element/synapse

In Nextcloud, I installed "DAV Push" 0.0.1, and restarted nginx/php_fpm (even though that wasn't documented as necessary).

In DAVx5, in settings, I clicked on the "UnifiedPush" setting, and it shows "Ready to receive push notifications (up.converstations.im)".
Under my (only, on the above NC server) connected account, I clicked into it and see a list of calendars.  I cliicked "refresh list" and got the moving stripe for about 30s, but on clicking a calendar no push.

I then deleted my account, and set it up again, using the nextcloud app flow.  Still no push on the calendar.
I looked at debug info on the phone, and saw a conversations UP endpoint, but nothing else that seemed relevant.
I then exported the debug zip to my nextcloud server.  In the logcat, I see what seems like too many push registration worker registrations:
```
09-16 14:34:09.924 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.930 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.936 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.942 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.947 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.953 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.958 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.963 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:09.968 17550 17568 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:10.619 17550 17567 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:10.623 17550 17567 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:10.627 17550 17567 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:10.632 17550 17567 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:10.636 17550 17567 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:15.683 17550 17567 I .push.PushRegistrationWorker: Running push registration worker
09-16 14:34:15.686 17550 17572 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=e714137e-e9cf-430d-b453-72f0fe9c77d9, tags={ at.bitfire.davdroid.push.PushRegistrationWorker } ]
09-16 14:34:20.991 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:24.315 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:24.799 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:26.374 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:26.910 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:29.001 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:33.143 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:34.910 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:39.922 17550 17567 I .push.PushRegistrationWorker: Running push registration worker
09-16 14:34:39.923 17550 17577 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=f835392d-7abf-479d-a4f3-1aa8f5776a08, tags={ at.bitfire.davdroid.push.PushRegistrationWorker } ]
09-16 14:34:50.333 17550 17550 I .push.PushRegistrationWorker: Enqueueing push registration worker
09-16 14:34:55.366 17550 17567 I .push.PushRegistrationWorker: Running push registration worker
09-16 14:34:55.368 17550 17572 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=39d5a789-1829-4a59-be1c-b1b8ca0ab648, tags={ at.bitfire.davdroid.push.PushRegistrationWorker } ]
```

I do have 9 calendars (some of which have tasks and journals) and 4 address books. but this is 23 Enqueuing lines.

I'm not sure what I should look at next.

**Comment by gdt** [comment]
I did find in NC logs:
```
"app":"no app in context","method":"PROPFIND","url":"/remote.php/dav/files/gdt/","message":"Token is not valid: Token is too short for a generated token, should be the password during basic auth","userAgent":"DAVx5/4.4.2-ose (2024/08/06; dav4jvm; okhttp/4.12.0) Android/13"
```
but I am guessing this is about the webdav mount I have configured, which seems to work.

**Comment by gdt** [comment]
After disabling and re-enabling DAV Push on nextcloud, and a bunch of retrying, my calendars are now showing push. 

Also, delay from clicking Save on an event in the nextcloud calendar app until it appeared on the phone's calendar was 12s, which means this is clearly working quite well.

Feel free to hit close after reading: This is now basically "it would be nice if there were more insight into how things are configured/working".

**Comment by gdt** [comment]
My nextcloud instance does not have any caching layers.  It's straight nginx/php_fpm.

I guess my  only remaining point is that running into issues is going to be normal enough that better information about what went wrong would be really useful.

**Comment by devvv4ever** [comment]
You could open a discussion in [bitfireAT/davx-ose](https://github.com/bitfireAT/davx5-ose/discussions) 

Maybe we can make the details there a bit more informative. First is of course to get in the basic features to be able to make a final release of it, so that it can clearly be spread to other *DAV servers/service providers.

**Comment by gdt** [comment]
Sure, I realize this is in an early state.   Where I'm coming from is that easing debugging for new people will help figure out where the rough edges are and end up with more testers.

Moved to a [davx 5 discussion](https://github.com/bitfireAT/davx5-ose/discussions/1030).
