### ISSUE TITLE
contacts push support

### ISSUE THREAD

**Issue by gdt** [bitfireAT/nc_ext_dav_push#28]
Details of my setup in #27.

After disabing/re-enabling, removing and adding account, I got push to work for calendars.   When I open details of an addressbook, I don't see that it is set for push.

I don't know if this is:
  - a bug in push for address books
  - push is only implemented for calendars, not contacts, in either DAVx5 or nc_ext_dav_push, but the README doesn't say that.  It does talk only about calendars.

it might be nice to always show a push support ilne, and instead of Subscribed, if not, to show some kind of error, like server does not advertise support, failed to register with on-device UP provider, failed to register UP data with dav server, etc.   I know that's details many might not care about, but it's a details page anyway.

**Comment by JonathanTreffler** [comment]
For the alpha release only calendars are supported by this extension (on the DAVx5 side contacts push is already implemented I think). Support will be added in a future release of this app over the next few months.

**Comment by JonathanTreffler** [comment]
Oops, I forgot this is a duplicate then, closing in favor of  #25
